### ISSUE TITLE
compile error in ubuntu 18

### ISSUE THREAD

**Issue by binlu1981** [Nextomics/NextPolish#32]
Hi, 

I have a compile error here. Any suggestions?

gcc -g -Wall -O2 -I. -I../../lib/htslib/ -I./lz4  -c -o bam_tview_curses.o bam_tview_curses.c
bam_tview_curses.c:41:10: fatal error: curses.h: No such file or directory
 #include <curses.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:133: recipe for target 'bam_tview_curses.o' failed
make[2]: *** [bam_tview_curses.o] Error 1

Thanks
Bin

**Comment by moold** [comment]
You should install ncurses and try `sudo apt-get install libncurses5-dev libncursesw5-dev`

**Comment by binlu1981** [comment]
Thanks. There is an error when run test data. 
[ERROR] 2020-06-30 09:43:36,569 polish_genome failed: please check the following
 logs:
Command terminated by signal 11

Any suggestions?

**Comment by moold** [comment]
This is another question, it does not have any relation with this thread, so you should open another issue, also need to give more details, such as version, log....

 I will close this issue.

**Comment by Neato-Nick** [comment]
I had the same problem, but this solution did not work for me. Because I'm working on an HPC, I:
* Run CentOS (no apt install)
* Don't have sudo (no yum install)

For anyone else finding this thread, here's what I did:
* [configure samtools without curses](https://www.biostars.org/p/205703/#205706) (cd util/samtools && autoheader && autoconf && ./configure --without-curses)
* compile NextPolish to get the tools added to NextPolish/bin (cd ../../make)

unfortunately samtools still isn't running for me but I'll open a different issue
$ bin/samtools
bin/samtools: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory
