### ISSUE TITLE
NextPolish-1.04 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wangzhennan14** [Nextomics/NextPolish#4]
Hi,
    I have installed NextPolish-1.04 successfully, but there was error when I ran it. The command line was: ../nextpolish run.cfg, and the error was: Segmentation fault (core dumped). What is the matter? Can you help me to solve it, thank you.
    wang

**Comment by moold** [comment]
Could you send me the input files? You can extract the related fasta/bam files only include the scaffolds/contigs which caused this errors?

**Comment by wangzhennan14** [comment]
@moold The input file is test_data. I just run nextpolish in test_data. The command line was ../nextpolish run.cfg.

**Comment by moold** [comment]
What is your system and gcc version?

**Comment by wangzhennan14** [comment]
@moold Linux login2 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux,  gcc version is 5.3.0.

**Comment by moold** [comment]
Could you provide the command that caused this errors directly ?  Please check the log and find the shell file (Not ../nextpolish run.cfg).

**Comment by wangzhennan14** [comment]
@moold There was no log file. When I run ./nextpolish, it shows Segmentation fault (core dumped).  I installed NextPolish successfully, why it can not run?

**Comment by moold** [comment]
This is very weird, because the main program: nextPolish is implemented  with python, and should do not have  Segmentation fault errors. If you have any log info, please paste it to here. 

And , I have two suggestions you can try:
1. try [this version](https://github.com/Nextomics/NextPolish/releases/download/v1.0.3/NextPolish-CentOS6.9.tgz)
2. set option: genome_size = your_genome_size, not auto.

**Comment by moold** [comment]
I will close this issue, but if you still have this problem, feel free to reopen it.
