### ISSUE TITLE
Using Mate-paired reads

### ISSUE THREAD

**Issue by rmarquezp** [Nextomics/NextPolish#56]
Hello, I am polishing a genome assembly using a combination of paired-end and mate-paired Illumina reads. Is it necessary to re-orient the mate-paired reads (which are oriented as RF instead or FR as in paired-end)? From the Bioinformatics paper it seems like NextPolish doesn't use pairing or orientation information, so reorienting should not be necessary, but I wanted to confirm. 

Thanks!

**Comment by moold** [comment]
Hi, you can not combine paired ends and paired Illumina readings for polishing. Because NextPolish will use the head ~50,000 reads to estimate the insert size, and use this insert size to filter the mapped reads. Therefore mate-paired reads may be filtered because their insert size is much larger than the paired end reads.

**Comment by rmarquezp** [comment]
Got it, thanks!
